# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181031_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='\u6743\u9650'),
        ),
    ]
